//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 生成的包含文件。
// 供 bbngame.rc 使用
//
#define IDD_BBNGAME_DIALOG              102
#define IDR_MAINFRAME                   128
#define IDD_GAME_DIALOG                 130
#define IDD_ANSDLG                      132
#define IDS_GAME1                       134
#define IDS_GAME2                       135
#define IDD_RULEDLG                     135
#define IDS_GAME3                       136
#define IDS_GAME4                       137
#define IDD_RULESETDIALOG               137
#define IDS_GAME5                       138
#define IDD_MONEYRULEDLG                138
#define IDS_GAME6                       139
#define IDS_GAME7                       140
#define IDS_GAME8                       141
#define IDS_GAME9                       142
#define IDS_GAME10                      143
#define IDS_GAME11                      144
#define IDD_GAMESHOWDLG                 144
#define IDS_GAME12                      145
#define IDS_GAME13                      146
#define IDD_DETAILDIALOG                146
#define IDS_GAME14                      147
#define IDS_GAME15                      148
#define IDD_WARNDIALOG                  148
#define IDS_GAME16                      149
#define IDS_GAME17                      150
#define IDD_SIDLOGINDIALOG              150
#define IDS_GAME18                      151
#define IDS_GAME19                      152
#define IDD_PARTDIALOG                  152
#define IDS_GAME20                      153
#define IDC_NAME_EDIT                   1000
#define IDC_PASSWD_EDIT                 1001
#define IDC_TAB                         1001
#define IDC_TOTALMONEY_EDIT             1002
#define IDC_USERCREDITEDIT              1002
#define IDC_INFOEDIT                    1003
#define IDC_TOTALBET_EDIT               1004
#define IDC_FAKEPROFIT_EDIT             1004
#define IDC_TOTALFAKEPROFITEDIT         1004
#define IDC_WIN_EDIT                    1005
#define IDC_LOSENUM_EDIT                1005
#define IDC_PAYOFF_EDIT                 1006
#define IDC_TOTALPROFITEDIT             1006
#define IDC_SIDEDIT                     1007
#define ID_SIDLOGINBTN                  1008
#define IDC_GAMEMODE                    1009
#define IDC_USEFAKEMONEYCB              1009
#define IDC_SETRULEBTN                  1010
#define IDC_SETUPRULEBTN                1010
#define IDC_HISTORYBTN                  1011
#define IDC_TOTALBETMONEY_EDIT          1012
#define IDC_TOTALBETEDIT                1012
#define IDC_FINDSIDBTN                  1013
#define IDC_SETUPBUTTON                 1014
#define IDC_USENEWBOX                   1015
#define IDC_USENEWGAMECB                1015
#define IDC_OMITMIDBOX                  1016
#define IDC_OMITMIDCB                   1016
#define IDC_WINNUM_EDIT                 1017
#define IDC_STARTGAMEBTN                1017
#define IDC_LOSESERIAL_EDIT             1018
#define IDC_TOTALMINPROFITEDIT          1018
#define IDC_DETAILPROFITBTN             1018
#define IDC_DOORLIST                    1019
#define IDC_WINSERIAL_EDIT              1019
#define IDC_TOTALMAXPROFITEDIT          1019
#define IDC_RULEBTN                     1019
#define IDC_RULETENDBTN                 1019
#define IDC_RULESETTAB                  1020
#define IDC_STOPGAMEBTN                 1020
#define IDC_MONEYLIST                   1021
#define IDC_LOSESTOPALLCB               1021
#define IDC_WINSTOPONECB                1022
#define IDC_LOSESTOPONECB               1023
#define IDC_RESETBTN                    1024
#define IDC_AVGUSEFAKECB                1025
#define IDC_ADDRULEBTN                  1026
#define IDC_WINSTOPALLCB                1026
#define IDC_DELRULEBTN                  1027
#define IDC_UPDATERULEBTN               1028
#define IDC_MONEYDLG_MONEYEDIT          1029
#define IDC_MONEYDLG_WINEDIT            1030
#define IDC_MONEYDL_LOSEEDIT            1031
#define IDC_ADDMONEYBTN                 1032
#define IDC_RULEDLG_RULEEDIT            1033
#define IDC_UPDATEMONEYBTN              1033
#define IDC_RULEDLG_BETEDIT             1034
#define IDC_DELMONEYBTN                 1034
#define IDC_MONEYDL_MIDEDIT             1035
#define IDC_RULEDLG_LIMITEDIT           1035
#define IDC_RULEFileCOMBO               1038
#define IDC_RULEFileEDIT                1039
#define IDC_SAVENEWRULEBTN              1040
#define IDC_CLOSERULEBTN                1041
#define IDC_NEWRULEBTN                  1042
#define IDC_SELECTRULECOMBO             1043
#define IDC_SETINRULECOMBOX             1043
#define IDC_DELOLDRULEBTN               1043
#define IDC_SELECTMONEYCOMBO            1044
#define IDC_SETBETRULECOMBOX            1044
#define IDC_SELECTRATEBUTTON            1045
#define IDC_SETCIRCLEBTN                1045
#define IDC_MAXPROFITEDIT               1046
#define IDC_SETAVGBTN                   1046
#define IDC_BETRULECOMBO                1047
#define IDC_SELECTRATEEDIT              1047
#define IDC_SETCIRCLEEDIT               1047
#define IDC_WINSTOPONEVALUEEDIT         1047
#define IDC_NEWBETRULEBTN               1048
#define IDC_MINPROFITEDIT               1048
#define IDC_SETAVGEDIT                  1048
#define IDC_NEWBETRULEFILEEDIT          1049
#define IDC_SETSTOPRULECOMBOX           1049
#define IDC_TARGETPROFITEDIT            1049
#define IDC_CLOSEBETRULEBTN             1050
#define IDC_CONFIRMRULEBTN              1050
#define IDC_TARGETLOSEEDIT              1050
#define IDC_SAVENEWBETRULEBTN           1051
#define IDC_BACKRATEEDIT                1051
#define IDC_KLINECTRL                   1052
#define IDC_ALLHIGHEDIT                 1053
#define IDC_CURPROFITEDIT               1053
#define IDC_GAMEMODECOMBOX              1053
#define IDC_CURHIGHEDIT                 1054
#define IDC_CURMAXPROFITEDIT            1054
#define IDC_BETPROFITEDIT               1055
#define IDC_ALLLOWEDIT                  1056
#define IDC_CURFAKEPROFITEDIT           1056
#define IDC_LOSESTOPALLVALUEEDIT        1056
#define IDC_CURLOWEDIT                  1057
#define IDC_CURMINPROFITEDIT            1057
#define IDC_BETRATEEDIT                 1058
#define IDC_LOSESTOPONEVALUEEDIT        1059
#define IDC_WINSTOPALLVALUEEDIT         1060
#define IDC_LOSESTARTTIMEEDIT           1062
#define IDC_WINSTARTTIMEEDIT            1063
#define IDC_ALLPLAYRADIO                1079
#define IDC_AVGPLAYRADIO                1080
#define IDC_RADIO                       1081
#define IDC_MOREPLAYRADIO               1081
#define IDC_REALPLAYRADIO               1082
#define IDC_DELOLDBETRULEBTN            1082
#define IDC_HIGHKLINERADIO              1083
#define IDC_NAMECHECK                   1083
#define IDC_MOREKLINERADIO              1084
#define IDC_DETAILBTN                   1085
#define IDC_PROFITEDIT                  1086
#define IDC_BETEDIT                     1087
#define IDC_ROADMAP                     1088
#define IDC_STATUSSTATIC                1089
#define IDC_BETCOLORSTATIC              1090
#define IDC_BANKERSTATIC                1091
#define IDC_DEATILLIST                  1091
#define IDC_PLAYERSTATIC                1092
#define IDC_MIDSTATIC                   1093
#define IDC_ALLTIMECHECK                1094
#define IDC_TIPEDIT                     1095
#define IDC_SCROLLBAR                   1096
#define ID_SIDLOGIN                     1098
#define IDC_GAMESTATUSEDIT              1101
#define IDC_TIMEEDIT                    1102

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        154
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1103
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
